spring.application.name=finance_tracker_service

server.port=8080
splitwise.api.url=https://secure.splitwise.com/api/v3.0
splitwise.api.key=YOUR_SPLITWISE_API_KEY

# This will run every hour
#cron.expression.processCSV=* * * * * *
# This will run every Sunday at midnight (00:00)
cron.expression.deleteCSV=0 0 0 * * SUN

csv.unprocessed.folderpath=./csvFiles/unprocessed
csv.processed.folderpath=./csvFiles/processed
csv.partiallyProcessed.folderpath=./csvFiles/partially_processed

# SQL Database
# MySQL Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/finance_tracker?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=YOUR_PASSWORD

# Hibernate JPA Configuration
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
